# k8s/jobs/setup-queues.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-queues
spec:
  template:
    spec:
      containers:
        - name: setup-queues
          image: samirsauma121/setup-queues:latest
          imagePullPolicy: Always
          command: ["node", "/app/setupQueues.js"]
          env:
            - name: RABBITMQ_USERNAME
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest
            - name: RABBITMQ_HOSTNAME
              value: amqp.default.svc.cluster.local
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_VHOST
              value: /
      restartPolicy: Never
  backoffLimit: 1
