apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
spec:
  replicas: 3 # Número de réplicas para escalabilidade horizontal
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
        - name: websocket-server
          image: samirsauma121/websocket-server:latest
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi" # Memória mínima garantida
              cpu: "250m"     # CPU mínima garantida
            limits:
              memory: "512Mi" # Memória máxima permitida
              cpu: "500m"     # CPU máxima permitida
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-server
spec:
  selector:
    app: websocket-server
  ports:
    - port: 8080
      targetPort: 8080