apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-producer
  template:
    metadata:
      labels:
        app: login-producer
    spec:
      containers:
        - name: login-producer
          image: samirsauma121/login-producer:latest
          env:
            - name: DB_NAME
              value: 55crypto
            - name: DB_USERNAME
              value: guest
            - name: DB_PASSWORD
              value: guest
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: AMQP_URL
              value: amqp://guest:guest@amqp:5672/
            - name: REDIS_URL
              value: redis://redis.default.svc.cluster.local:6379
            - name: JWT_SECRET
              value: asdasdasdasdasdasadasdadad
            - name: PORT
              value: "3001"
            - name: WEBSOCKET_URL
              value: ws://websocket-server.default.svc.cluster.local:8080
            - name: MAILGUN_API_KEY
              value: <sua-mailgun-api-key>
            - name: MAILGUN_DOMAIN
              value: <seu-mailgun-domain>
            - name: RABBITMQ_USERNAME
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest
            - name: RABBITMQ_HOSTNAME
              value: amqp.default.svc.cluster.local
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_VHOST
              value: /
          ports:
            - containerPort: 3001
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: login-producer
spec:
  selector:
    app: login-producer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001